version: '3.7'
services:
    # web:
    #     image: 
    #     depends_on: postgredb

    postgredb:
        image: postgres
        restart: always
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432
        volumes:
            # Entrypoint for postgresDB
            - ./docker-scripts/docker-entrypoint-init.d:/docker-entrypoint-initdb.d/
            - ./db:/var/lib/postgresql/data

    dbmgmt:
        image: adminer
        restart: always
        depends_on: 
            - postgredb
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgredb
            ADMINER_DEFAULT_DB_DRIVER: postgresql
            ADMINER_DEFAULT_DB_NAME: vmctap
            ADMINER_DESIGN: nette
            ADMINER_PLUGINS: tables-filter tinymce edit-foreign
        # volumes:
        #     - /var/www/html/plugins-enabled/

# volumes:
