version: '3.7'

services:

  postgredb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      # Entrypoint for postgresDB
      - "./docker/docker-scripts/docker-entrypoint-init.d:/docker-entrypoint-initdb.d/"
      - "db-data:/var/lib/postgresql/data"
      - "./docker/dockerFiles:/opt/data"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgredb
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    volumes:
      - "./docker-scripts/pgadmin/dbServer.json:/pgadmin4/servers.json"

  flask:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./app:/code/app
    depends_on:
      - postgredb

volumes:
    db-data: